<?php
$salesmen = $this->getSalesmen();
$salesmen_address = $this->getSalesmenAddress();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>salesmen-edit</title>
</head>
<body>
<form method="POST" action="index.php?c=salesman&a=update" align="center">
<table width="100%">
	<tr>
		<td><h2 align="left">EDIT VENDOR</h2></td>
		<td><h3 align="right"><a href="index.php?c=salesman&a=grid">CANCEL</a></h3></td>
		<td><h3 align="right"><button>SAVE</button></h3></td>
	</tr>
</table>
<table border="3" width="100%" cellpadding="10">

		<tr>		
			<td colspan="2"><h3>SALESMAN INFORMATION</h3></td>
		</tr>

		<tr>
			<td>first_Name:</td>
			<td><input type="text" name="salesman[first_name]" value="<?php echo $salesmen['first_name']?>"></td>
			<input type="hidden" name="id" value="<?php echo $salesmen['salesmen_id'] ?>">
		</tr>
		
		<tr>
			<td>last_Name:</td>
			<td><input type="text" name="salesman[last_name]" value="<?php echo $salesmen['last_name']?>"></td>
		</tr>

		<tr>
			<td>Email:</td>
			<td><input type="text" name="salesman[email]" value="<?php echo $salesmen['email']?>"></td>
		</tr>

		<?php $genderOptions = [1=>"Male" , 2=>"Female" , 3=>"Others"];?>
		<tr>
			<td>Gender</td>
			<td>
				<select name="salesman[gender]">
				<?php foreach ($genderOptions as $value => $label):?>
				<option value="<?php echo $value;?>" <?php if ($salesmen['gender']==$value)echo "selected";?>><?php echo $label;?></option>
				<?php endforeach; ?>
			</select></td>
		</tr>

		<tr>
			<td>Mobile:</td>
			<td><input type="text" name="salesman[mobile]" value="<?php echo $salesmen['mobile']?>"></td>
		</tr>

		<?php $statusOptions = [1=>"Active" , 2=>"Inactive"];?>
		<tr>
			<td>Status</td>
			<td>
				<select name="salesman[status]">
				<?php foreach ($statusOptions as $value => $label):?>
				<option value="<?php echo $value;?>" <?php if ($salesmen['status']==$value)echo "selected";?>><?php echo $label;?></option>
				<?php endforeach; ?>
			</select></td>
		</tr>
		
		<tr>
			<td>Company:</td>
			<td><input type="text" name="salesman[company]" value="<?php echo $salesmen['company']?>"></td>
		</tr>

		<tr>		
			<td colspan="2"><h3>ADDRESS INFORMATION</h3></td>
		</tr>
		
		<tr>
			<td>address</td>
			<td><input type="text" name="salesman_address[address]" value="<?php echo $salesmen_address['address']?>"></td>
		</tr>
		
		<tr>
			<td>city</td>
			<td><input type="text" name="salesman_address[city]" value="<?php echo $salesmen_address['city']?>"></td>
		</tr>

		<tr>
			<td>state</td>
			<td><input type="text" name="salesman_address[state]" value="<?php echo $salesmen_address['state']?>"></td>
		</tr>

		<tr>
			<td>country</td>
			<td><input type="text" name="salesman_address[country]"value="<?php echo $salesmen_address['country']?>"></td>
		</tr>

		<tr>
			<td>zipcode</td>
			<td><input type="text" name="salesman_address[zipcode]" value="<?php echo $salesmen_address['zipcode']?>"></td>
		</tr>

		
</table>
</form>
</body>
</html>