<?php
$category = $this->getData('category');
$categories = $this->getData('categories');
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
</head>
<body>
<table border="0" width="100%" cellpadding="20">
	<tr>
		<td>
			<h1 align="center">UPDATE CATEGORY DATA</h1>
		</td>
	</tr>
</table>
<form method="POST" action="index.php?c=category&a=save&id=<?php echo $category->category_id;?>" align="center">
<table border="3" width="100%" cellpadding="10" align="center">
	<tr>
		<td>Parent Category</td>
		<td><select name="category[parent_id]">
			<?php foreach ($categories as $category1): ?>
				<option value="<?php echo $category1->category_id; ?>"><?php echo $category1->path;?></option>
			<?php endforeach ?>
		</select></td>
	</tr>
	<tr>
		<td>Name</td>
		<td><input type="text" name="category[name]" value="<?php echo $category->name; ?>"></td>
	</tr>
	<?php $statusOptions = [1=>"Active" , 2=>"Inactive"];?>
	<tr>
		<td>Status</td>
		<td>
			<select name="category[status]">
			<?php foreach ($statusOptions as $value => $label):?>
			<option value="<?php echo $value; ?>" <?php if ($category->status==$value)echo "selected";?>><?php echo $label;?></option>
			<?php endforeach; ?>
		</select>
		</td>
	</tr>
	<tr>
		<td>Description</td>
		<td><input type="text" name="category[description]" value="<?php echo $category->description; ?>"></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td><button type="submit" name="update" value="update">UPDATE</button></td>
	</tr>
</table>
</form>
</body>
</html>
<br>
<br>
<div align="center"><a href="index.php?c=category&a=grid">CANCEL</a></div>