<?php
$shipping = $this->getData();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
</head>
<body>
<table border="0" width="100%" cellpadding="20">
	<tr>
		<td>
			<h1 align="center">SAVE SHIPPING DATA</h1>
		</td>
	</tr>
</table>
<form method="POST" action="index.php?c=shippingMethod&a=save&id=<?php echo $shipping->shipping_method_id;?>" align="center">
<table border="3" width="100%" cellpadding="10" align="center">
	<tr>
		<td>Name</td>
		<td><input type="text" name="shipping[name]" value="<?php echo $shipping->name; ?>"></td>
		<!-- <input type="hidden" name="id" value="<?php echo $shipping->shipping_method_id ?>"> -->
	</tr>
	<tr>
		<td>Amount</td>
		<td><input type="text" name="shipping[amount]" value="<?php echo $shipping->amount; ?>"></td>
	</tr>
	<?php $statusOptions = $shipping->getTableObject()->getStatusOptions() ?>
	<tr>
		<td>Status</td>
		<td>
			<select name="shipping[status]">
			<?php foreach ($statusOptions as $value => $label):?>
			<option value="<?php echo $value; ?>" <?php if ($shipping->status == $value)echo "selected";?>><?php echo $label;?></option>
			<?php endforeach; ?>
		</select>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td><button type="submit" name="update" value="update">UPDATE</button></td>
	</tr>
</table>
</form>
</body>
</html>
<br>
<br>
<div align="center"><a href="index.php?c=shipping&a=grid">CANCEL</a></div>