<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<table width="100%">
	<tr>
		<td><h2 align="center">ADD IMAGE</h2></td>
	</tr>
</table>
	<div>
		<form method="POST" action="index.php?c=product_media&a=insert&product_id=<?php echo $_GET['product_id']; ?>" enctype="multipart/form-data">
			<table border="3" width="100%" cellpadding="10">
				
				<tr>
					<td>Name</td>
					<td><input type="text" name="name"></td>
				</tr>
				<tr>
					<td>Browse Image</td>
					<td><input type="file" name="image"></td>
				</tr>
				<tr align="center">
					<td colspan="2"><input type="submit"></td>
				</tr>
			</table>
		</form>
	</div>
</body>
</html>