<?php
$payments = $this->getData();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>index</title>
</head>
<body>
	<div>
		<div class="header">
			<?php require_once'View/html/Header.phtml';?>
		</div>

		<div class="content">
		<table width="100%" cellspacing="10px" cellpadding="10px" class="css">
				<tr>
					<td><h2 align="left">MANAGE PAYMENTS</h2></td>
					<td><h3 align="right"><a href="index.php?c=paymentMethod&a=add">ADD PAYMENT</a></h3></td>
				</tr>
		</table>

	<table border="3" width="100%" align="center" cellpadding="4px" cellspacing="4px">
	 	<tr>
	 		<th>PAYMENT_ID</th>
	 		<th>NAME</th>
	 		<th>STATUS</th>
	 		<th>CREATED_AT</th>
	 		<th>UPDATED_AT</th>
	 		<th colspan="2">OPERATIONS</th>
	 	</tr>
	 	<?php  foreach ($payments as $payment): ?>
	 	<tr align="center">
	 		<td><?php echo $payment->payment_method_id ?></td>
	 		<td><?php echo $payment->name ?></td>
	 		<td><?php echo $payment->status ?></td>
	 		<td><?php echo $payment->created_at ?></td>
	 		<td><?php echo $payment->updated_at ?></td>
	 		<td><a href="index.php?c=paymentMethod&a=edit&id=<?php echo $payment->payment_method_id ?>">EDIT</a></td>
	 		<td><a href="index.php?c=paymentMethod&a=delete&id=<?php echo $payment->payment_method_id?>">DELETE</a></td>
	 	</tr>
	 	<?php endforeach ?>
	</table>
	</div>
	 <div class="footer" align="center"><?php require_once 'view/Html/footer.phtml';?></div>
</div>
</body>
</html>
