<?php
$payment = $this->getData();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
</head>
<body>
<table border="0" width="100%" cellpadding="20">
	<tr>
		<td>
			<h1 align="center">SAVE PAYMENT DATA</h1>
		</td>
	</tr>
</table>
<form method="POST" action="index.php?c=paymentMethod&a=save&id=<?php echo $payment->payment_method_id;?>" align="center">
<table border="3" width="100%" cellpadding="10" align="center">
	<tr>
		<td>Name</td>
		<td><input type="text" name="payment[name]" value="<?php echo $payment->name; ?>"></td>
	</tr>
	<?php $statusOptions = [1=>"Active" , 2=>"Inactive"];?>
	<tr>
		<td>Status</td>
		<td>
			<select name="payment[status]">
			<?php foreach ($statusOptions as $value => $label):?>
			<option value="<?php echo $value; ?>" <?php if ($payment->status ==$value)echo "selected";?>><?php echo $label;?></option>
			<?php endforeach; ?>
		</select>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td><button type="submit" name="update" value="update">UPDATE</button></td>
	</tr>
</table>
</form>
</body>
</html>
<br>
<br>
<div align="center"><a href="index.php?c=paymentMethod&a=grid">CANCEL</a></div>